// Moroccan pitch data - Casablanca zones only
const pitchesData = [
  {
    id: 1,
    name: "Terrain Al Amal",
    city: "Casablanca",
    zone: "Hay Mohammadi",
    sport: "Football",
    price: 350,
    description:
      "A well-maintained neighborhood pitch with artificial turf, perfect for friendly matches. Floodlights available for evening games.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Artificial Turf", "Floodlights", "Changing Rooms", "Parking"],
    capacity: "10 vs 10",
    openHours: "08:00 - 23:00",
    phone: "+212 6 12 34 56 78",
  },
  {
    id: 2,
    name: "Complexe Sportif Sidi Moumen",
    city: "Casablanca",
    zone: "Sidi Moumen",
    sport: "Football",
    price: 400,
    description:
      "Community sports complex with two football pitches. Popular among local teams for training sessions and weekend tournaments.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Natural Grass", "Floodlights", "Cafeteria", "Showers"],
    capacity: "11 vs 11",
    openHours: "07:00 - 22:00",
    phone: "+212 6 23 45 67 89",
  },
  {
    id: 3,
    name: "Terrain Ain Sebaa",
    city: "Casablanca",
    zone: "Ain Sebaa",
    sport: "Football",
    price: 300,
    description:
      "Affordable pitch in the industrial quarter. Great for after-work games with colleagues. Basic but functional facilities.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Artificial Turf", "Floodlights", "Water Fountain"],
    capacity: "7 vs 7",
    openHours: "16:00 - 23:00",
    phone: "+212 6 34 56 78 90",
  },
  {
    id: 4,
    name: "Club Basket Maarif",
    city: "Casablanca",
    zone: "Maarif",
    sport: "Basketball",
    price: 250,
    description:
      "Indoor basketball court in a residential area. Well-maintained hardwood floor and proper basketball hoops.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Indoor Court", "Air Conditioning", "Locker Rooms", "Scoreboard"],
    capacity: "5 vs 5",
    openHours: "09:00 - 21:00",
    phone: "+212 6 45 67 89 01",
  },
  {
    id: 5,
    name: "Terrain Derb Sultan",
    city: "Casablanca",
    zone: "Derb Sultan",
    sport: "Football",
    price: 280,
    description:
      "Historic neighborhood pitch in the heart of the old city. A favorite spot for local youth and amateur teams.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Artificial Turf", "Floodlights", "Seating Area"],
    capacity: "6 vs 6",
    openHours: "08:00 - 22:00",
    phone: "+212 6 56 78 90 12",
  },
  {
    id: 6,
    name: "Tennis Club Anfa",
    city: "Casablanca",
    zone: "Anfa",
    sport: "Tennis",
    price: 180,
    description:
      "Quiet tennis courts in the upscale Anfa neighborhood. Clay surface with equipment rental available.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Clay Courts", "Equipment Rental", "Coaching Available", "Cafe"],
    capacity: "Singles/Doubles",
    openHours: "07:00 - 20:00",
    phone: "+212 6 67 89 01 23",
  },
  {
    id: 7,
    name: "Salle Omnisport Hay Hassani",
    city: "Casablanca",
    zone: "Hay Hassani",
    sport: "Volleyball",
    price: 200,
    description:
      "Multi-purpose sports hall with dedicated volleyball courts. Used by local clubs for training and competitions.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Indoor Court", "Professional Net", "Changing Rooms", "Bleachers"],
    capacity: "6 vs 6",
    openHours: "10:00 - 21:00",
    phone: "+212 6 78 90 12 34",
  },
  {
    id: 8,
    name: "Paddle Club Bouskoura",
    city: "Casablanca",
    zone: "Bouskoura",
    sport: "Paddle",
    price: 220,
    description:
      "Modern paddle tennis facility near the forest. Three courts available with glass walls and artificial turf.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Glass Courts", "Forest View", "Pro Shop", "Lounge Area"],
    capacity: "2 vs 2",
    openHours: "08:00 - 22:00",
    phone: "+212 6 89 01 23 45",
  },
  {
    id: 9,
    name: "Terrain Sbata",
    city: "Casablanca",
    zone: "Sbata",
    sport: "Football",
    price: 320,
    description:
      "Local football pitch popular among residents. Well-lit for evening matches with a friendly community atmosphere.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Artificial Turf", "Floodlights", "Parking", "Refreshments"],
    capacity: "8 vs 8",
    openHours: "07:00 - 23:00",
    phone: "+212 6 90 12 34 56",
  },
  {
    id: 10,
    name: "Complexe Sportif Oulfa",
    city: "Casablanca",
    zone: "Oulfa",
    sport: "Basketball",
    price: 150,
    description:
      "Affordable outdoor basketball courts in Oulfa. Well-lit for evening games with a friendly atmosphere.",
    image: "images/pitch placeholder.jpg",
    amenities: ["Outdoor Courts", "Floodlights", "Water Fountain", "Benches"],
    capacity: "3 vs 3 / 5 vs 5",
    openHours: "06:00 - 22:00",
    phone: "+212 6 01 23 45 67",
  },
];

// Export for use in other scripts
if (typeof module !== "undefined" && module.exports) {
  module.exports = pitchesData;
}
